---


- name: install webmin
  apt:
    deb: "{{ webmin_dl_url }}"

- name: install packages required by docker
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes

- name: add docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: add docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present

- name: install (or update) docker package
  apt:
    name: "docker-engine"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: yes
  notify:
    - systemd daemon-reload
    - restart docker service

- name: start docker
  service:
    name: docker
    state: started

- name: create user for docker tasks
  user:
    name: "{{ my_username }}"
    comment: user for media server tasks
    uid: "{{ docker_puid }}"
    groups: docker

- name: docker tasks for base-setup
  docker_service:
    project_name: base-setup
    definition:
      version: "2"
      services:
        watchtower:
          container_name: watchtower
          restart: always
          image: v2tec/watchtower
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          command: --schedule "0 0 4 * * *" --cleanup
        portainer:
          image: portainer/portainer
          restart: always
          container_name: portainer
          command: --templates http://templates/templates.json
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/"{{ my_username }}"/docker/portainer/data:/data
          ports:
            - "9000:9000"
          environment:
            - TZ="{{ my_tz }}"
